### ISSUE TITLE
컴포넌트 npm 배포

### ISSUE THREAD

**Issue by euan-lee** [prgrms-web-devcourse/OFF_Design_System#2]
그냥 한번 써봄...

**Comment by jgjgill** [comment]
최근 자료이자 빠르게 적용할 수 있어 보이는 자료 링크 공유합니다..!
Vite + Typescript 환경
[Creating a Component Library Fast🚀(using Vite's library mode)](https://dev.to/receter/how-to-create-a-react-component-library-using-vites-library-mode-4lma)
